const fs = require('fs');

const eventsArray = `[
    // TECHNOLOGY
    {
      title: 'India AI Builders Summit 2026',
      shortDescription: 'Explore the future of artificial intelligence and its real-world applications.',
      description: 'Join leading AI researchers and industry pioneers for a full-day summit on machine learning, deep learning, generative AI, and responsible AI practices. Hands-on workshops, keynotes, and networking sessions included.',
      category: 'technology',
      venue: 'Bangalore International Centre',
      city: 'Bengaluru',
      address: 'Domlur, Bengaluru',
      startDate: new Date(new Date().getFullYear() + 2, 4, 15),
      endDate: new Date(new Date().getFullYear() + 2, 4, 16),
      startTime: '09:00 AM',
      organizer: 'TechVista Foundation',
      imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
      price: 1499,
      capacity: 350,
      availableSeats: 350,
      status: 'published',
      featured: true,
      tags: ['ai', 'machine-learning', 'deep-learning', 'technology'],
      createdBy: adminId,
    },
    {
      title: 'Cloud & DevOps Connect Kolkata',
      shortDescription: 'A practical technology conference covering cloud deployment and DevOps.',
      description: 'A practical technology conference covering cloud deployment, containers, CI/CD, observability, and modern DevOps workflows. Perfect for system administrators and cloud engineers.',
      category: 'technology',
      venue: 'Biswa Bangla Convention Centre',
      city: 'Kolkata',
      address: 'New Town, Kolkata',
      startDate: new Date(new Date().getFullYear() + 2, 6, 10),
      endDate: new Date(new Date().getFullYear() + 2, 6, 11),
      startTime: '10:00 AM',
      organizer: 'CloudNative India',
      imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
      price: 799,
      capacity: 250,
      availableSeats: 250,
      status: 'published',
      featured: false,
      tags: ['cloud', 'devops', 'kubernetes', 'aws'],
      createdBy: adminId,
    },
    {
      title: 'Cybersecurity Future Forum',
      shortDescription: 'Security-focused event featuring discussions on zero trust and cyber threats.',
      description: 'A security-focused event featuring discussions on application security, zero trust, cloud security, and emerging cyber threats. Learn from top security researchers and ethical hackers.',
      category: 'technology',
      venue: 'HITEX Exhibition Centre',
      city: 'Hyderabad',
      address: 'Hitech City, Hyderabad',
      startDate: new Date(new Date().getFullYear() + 2, 8, 5),
      startTime: '09:30 AM',
      organizer: 'InfoSec Hub',
      imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80',
      price: 999,
      capacity: 300,
      availableSeats: 300,
      status: 'published',
      featured: true,
      tags: ['security', 'cybersecurity', 'infosec', 'technology'],
      createdBy: adminId,
    },
    // MUSIC
    {
      title: 'Kolkata Indie Music Evening',
      shortDescription: 'Three days of independent music, art installations, and food.',
      description: 'Soundscape brings together India\'s finest independent musicians across genres — rock, electronic, folk fusion, jazz, and hip-hop. Enjoy stages, food stalls, art exhibits, and late-night sets.',
      category: 'music',
      venue: 'Nazrul Mancha',
      city: 'Kolkata',
      address: 'Rabindra Sarobar',
      startDate: new Date(new Date().getFullYear() + 2, 2, 12),
      startTime: '06:00 PM',
      organizer: 'SoundWave Productions',
      imageUrl: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&q=80',
      price: 599,
      capacity: 800,
      availableSeats: 800,
      status: 'published',
      featured: true,
      tags: ['music', 'indie', 'live-performance'],
      createdBy: adminId,
    },
    {
      title: 'Mumbai Electronic Nights',
      shortDescription: 'An unforgettable night of EDM with international DJs.',
      description: 'Pulse brings world-class electronic music to Mumbai with headliners from Europe and home-grown talents. State-of-the-art sound system, laser shows, VIP lounges, and an open-air dance floor under the stars.',
      category: 'music',
      venue: 'Jio World Drive',
      city: 'Mumbai',
      address: 'BKC, Mumbai',
      startDate: new Date(new Date().getFullYear() + 2, 11, 31),
      startTime: '08:00 PM',
      organizer: 'Pulse Entertainment',
      imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80',
      price: 1999,
      capacity: 1200,
      availableSeats: 1200,
      status: 'published',
      featured: true,
      tags: ['edm', 'electronic', 'music', 'nightlife'],
      createdBy: adminId,
    },
    {
      title: 'Bengaluru Acoustic Sessions',
      shortDescription: 'An enchanting evening of acoustic performances and soulful singing.',
      description: 'Experience the magic of acoustic music with acclaimed artists and indie singers. The 3-hour concert features relaxing tunes, accompanied by a beautiful visual aesthetic.',
      category: 'music',
      venue: 'Good Shepherd Auditorium',
      city: 'Bengaluru',
      address: 'Residency Road',
      startDate: new Date(new Date().getFullYear() + 2, 7, 20),
      startTime: '07:00 PM',
      organizer: 'Bengaluru Music Academy',
      imageUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80',
      price: 499,
      capacity: 500,
      availableSeats: 500,
      status: 'published',
      featured: false,
      tags: ['acoustic', 'music', 'live'],
      createdBy: adminId,
    },
    // BUSINESS
    {
      title: 'Startup Growth Summit India',
      shortDescription: 'Accelerate your startup journey with mentorship from unicorn founders.',
      description: 'A 2-day intensive bootcamp for early-stage founders covering fundraising, product-market fit, growth hacking, team building, and investor pitching. Features mock pitch sessions with real VCs and networking dinners.',
      category: 'business',
      venue: 'NESCO Convention Centre',
      city: 'Mumbai',
      address: 'Goregaon East',
      startDate: new Date(new Date().getFullYear() + 2, 3, 10),
      endDate: new Date(new Date().getFullYear() + 2, 3, 11),
      startTime: '09:00 AM',
      organizer: 'LaunchPad India',
      imageUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80',
      price: 1299,
      capacity: 400,
      availableSeats: 400,
      status: 'published',
      featured: true,
      tags: ['startup', 'entrepreneurship', 'business', 'investment'],
      createdBy: adminId,
    },
    {
      title: 'Young Entrepreneurs Networking Day',
      shortDescription: 'Meet and collaborate with young entrepreneurs and innovators.',
      description: 'A networking-focused day full of speed networking, collaborative problem-solving rounds, and keynotes from successful young leaders under 30.',
      category: 'business',
      venue: 'India Habitat Centre',
      city: 'Delhi',
      address: 'Lodhi Road',
      startDate: new Date(new Date().getFullYear() + 2, 5, 25),
      startTime: '10:00 AM',
      organizer: 'Young Leaders Collective',
      imageUrl: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&q=80',
      price: 699,
      capacity: 250,
      availableSeats: 250,
      status: 'published',
      featured: false,
      tags: ['networking', 'entrepreneurship', 'leadership'],
      createdBy: adminId,
    },
    {
      title: 'Future of Digital Commerce Forum',
      shortDescription: 'Discover the next big trends in ecommerce, D2C, and digital payments.',
      description: 'Join industry experts from top ecommerce giants to discuss D2C brands, quick commerce, logistics innovations, and the digital payment landscape in India.',
      category: 'business',
      venue: 'The Chancery Pavilion',
      city: 'Bengaluru',
      address: 'Residency Road',
      startDate: new Date(new Date().getFullYear() + 2, 9, 14),
      startTime: '09:30 AM',
      organizer: 'CommerceNext India',
      imageUrl: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800&q=80',
      price: 999,
      capacity: 300,
      availableSeats: 300,
      status: 'published',
      featured: false,
      tags: ['ecommerce', 'd2c', 'business', 'retail'],
      createdBy: adminId,
    },
    // WORKSHOPS
    {
      title: 'MERN Stack Project Bootcamp',
      shortDescription: 'Build production-grade apps with React and Node.js.',
      description: 'A hands-on workshop covering React, Node.js, Express, MongoDB, authentication patterns, database integration, and deployment. Bring your laptop and build a real project by the end of the day.',
      category: 'workshop',
      venue: 'Sector V Innovation Hub',
      city: 'Kolkata',
      address: 'Salt Lake Sector V',
      startDate: new Date(new Date().getFullYear() + 2, 1, 15),
      startTime: '10:00 AM',
      organizer: 'DevCraft Academy',
      imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
      price: 499,
      capacity: 80,
      availableSeats: 80,
      status: 'published',
      featured: true,
      tags: ['react', 'node', 'javascript', 'web-development'],
      createdBy: adminId,
    },
    {
      title: 'UI UX Design Hands-On Workshop',
      shortDescription: 'Learn design methodologies and Figma prototyping.',
      description: 'Master user experience design in this intensive workshop. Learn problem framing, wireframing, high-fidelity UI design in Figma, and user testing. Work on a real case study with your team.',
      category: 'workshop',
      venue: 'MCCIA Trade Tower',
      city: 'Pune',
      address: 'Senapati Bapat Road',
      startDate: new Date(new Date().getFullYear() + 2, 8, 20),
      startTime: '09:00 AM',
      organizer: 'DesignLab India',
      imageUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
      price: 399,
      capacity: 60,
      availableSeats: 60,
      status: 'published',
      featured: false,
      tags: ['ux', 'design', 'figma', 'ui'],
      createdBy: adminId,
    },
    {
      title: 'Git GitHub and Open Source Workshop',
      shortDescription: 'Start your open-source journey by learning version control basics.',
      description: 'A free workshop for students and professionals covering Git basics, branching strategies, resolving merge conflicts, and making your first open-source contribution on GitHub.',
      category: 'workshop',
      venue: 'WeWork Galaxy',
      city: 'Bengaluru',
      address: 'Residency Road',
      startDate: new Date(new Date().getFullYear() + 2, 6, 25),
      startTime: '11:00 AM',
      organizer: 'OpenSource India',
      imageUrl: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&q=80',
      price: 0,
      capacity: 100,
      availableSeats: 100,
      status: 'published',
      featured: true,
      tags: ['git', 'github', 'open-source', 'coding'],
      createdBy: adminId,
    },
    // SPORTS
    {
      title: 'Kolkata City 10K Run',
      shortDescription: '10K and 5K categories for runners of all levels.',
      description: 'Join thousands of runners in Kolkata\'s annual health marathon. Categories include 5K Fun Run and 10K Competitive. All participants receive medals, timing chips, hydration packs, and event t-shirts.',
      category: 'sports',
      venue: 'Eco Park',
      city: 'Kolkata',
      address: 'New Town',
      startDate: new Date(new Date().getFullYear() + 2, 10, 14),
      startTime: '05:30 AM',
      organizer: 'Kolkata Runners Club',
      imageUrl: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&q=80',
      price: 499,
      capacity: 1000,
      availableSeats: 1000,
      status: 'published',
      featured: true,
      tags: ['marathon', 'running', 'fitness', 'sports'],
      createdBy: adminId,
    },
    {
      title: 'Corporate Football Championship',
      shortDescription: 'Inter-company football tournament with exciting prizes.',
      description: 'Assemble your corporate team and compete in Bengaluru\'s biggest inter-company 5-a-side football league. Knockout format, professional refereeing, and trophies for the top 3 teams. Great team-building activity!',
      category: 'sports',
      venue: 'Bangalore Football Stadium',
      city: 'Bengaluru',
      address: 'Ashok Nagar',
      startDate: new Date(new Date().getFullYear() + 2, 4, 18),
      endDate: new Date(new Date().getFullYear() + 2, 4, 19),
      startTime: '08:00 AM',
      organizer: 'Corporate Sports League',
      imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&q=80',
      price: 299,
      capacity: 600,
      availableSeats: 600,
      status: 'published',
      featured: false,
      tags: ['football', 'sports', 'corporate', 'team'],
      createdBy: adminId,
    },
    {
      title: 'Mumbai Fitness Challenge 2026',
      shortDescription: 'A multi-disciplinary fitness challenge spanning crossfit, lifting, and agility.',
      description: 'Test your limits at the Mumbai Fitness Challenge. Compete in individual or team categories across obstacle courses, weightlifting, and high-intensity interval training challenges.',
      category: 'sports',
      venue: 'MMRDA Grounds',
      city: 'Mumbai',
      address: 'BKC, Mumbai',
      startDate: new Date(new Date().getFullYear() + 2, 1, 8),
      startTime: '07:00 AM',
      organizer: 'FitIndia Events',
      imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
      price: 699,
      capacity: 750,
      availableSeats: 750,
      status: 'published',
      featured: true,
      tags: ['fitness', 'sports', 'challenge', 'crossfit'],
      createdBy: adminId,
    },
    // COMMUNITY
    {
      title: 'Clean City Volunteer Drive',
      shortDescription: 'Volunteer for a city-wide cleanup and tree plantation drive.',
      description: 'Be part of Kolkata\'s biggest community cleanup event. Activities include lakeside cleaning, tree planting, waste segregation awareness, and eco-craft workshops for kids. All volunteers receive certificates and refreshments.',
      category: 'community',
      venue: 'Rabindra Sarobar',
      city: 'Kolkata',
      address: 'Southern Avenue',
      startDate: new Date(new Date().getFullYear() + 2, 3, 22),
      startTime: '07:00 AM',
      organizer: 'Green Earth Kolkata',
      imageUrl: 'https://images.unsplash.com/photo-1593113563332-e14b53ef1788?w=800&q=80',
      price: 0,
      capacity: 300,
      availableSeats: 300,
      status: 'published',
      featured: true,
      tags: ['community', 'volunteer', 'environment', 'social'],
      createdBy: adminId,
    },
    {
      title: 'Youth Community Leadership Meetup',
      shortDescription: 'Connect with local leaders and discuss community initiatives.',
      description: 'A platform for young minds to discuss civic issues, community leadership, and grassroots initiatives. Network with NGO founders and local community organizers.',
      category: 'community',
      venue: 'Lodhi Garden Community Space',
      city: 'Delhi',
      address: 'Lodhi Estate',
      startDate: new Date(new Date().getFullYear() + 2, 7, 12),
      startTime: '04:00 PM',
      organizer: 'Delhi Youth Forum',
      imageUrl: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&q=80',
      price: 0,
      capacity: 150,
      availableSeats: 150,
      status: 'published',
      featured: false,
      tags: ['community', 'leadership', 'youth', 'networking'],
      createdBy: adminId,
    },
    {
      title: 'Tech for Social Good Meetup',
      shortDescription: 'How technology is driving social impact across India.',
      description: 'Meet developers, designers, and NGO workers collaborating to build open-source tools for healthcare, education, and disaster relief. Explore active projects and find out how you can contribute your skills.',
      category: 'community',
      venue: 'T-Hub',
      city: 'Hyderabad',
      address: 'Knowledge City',
      startDate: new Date(new Date().getFullYear() + 2, 5, 20),
      startTime: '10:00 AM',
      organizer: 'Tech4Good India',
      imageUrl: 'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?w=800&q=80',
      price: 0,
      capacity: 200,
      availableSeats: 200,
      status: 'published',
      featured: true,
      tags: ['community', 'tech', 'social-good', 'ngo'],
      createdBy: adminId,
    },
    // ARTS
    {
      title: 'Contemporary India Art Exhibition',
      shortDescription: 'Discover incredible artworks from rising Indian artists.',
      description: 'A beautiful exhibition showcasing modern Indian contemporary art, featuring sculptures, canvas paintings, and digital artworks from over 50 artists nationwide.',
      category: 'arts',
      venue: 'Triveni Kala Sangam',
      city: 'Delhi',
      address: 'Mandi House',
      startDate: new Date(new Date().getFullYear() + 2, 9, 10),
      endDate: new Date(new Date().getFullYear() + 2, 9, 20),
      startTime: '11:00 AM',
      organizer: 'Delhi Art Collective',
      imageUrl: 'https://images.unsplash.com/photo-1536924940846-227afb31e2a5?w=800&q=80',
      price: 199,
      capacity: 500,
      availableSeats: 500,
      status: 'published',
      featured: true,
      tags: ['art', 'exhibition', 'painting', 'contemporary'],
      createdBy: adminId,
    },
    {
      title: 'Kolkata Creative Photography Walk',
      shortDescription: 'Capture Kolkata\'s colonial architecture and street life.',
      description: 'A guided photography walk through Kolkata\'s heritage lanes. Professional photographers guide you on composition, light, and storytelling through images. Great for beginners and pros alike.',
      category: 'arts',
      venue: 'Victoria Memorial Gate',
      city: 'Kolkata',
      address: 'Queens Way',
      startDate: new Date(new Date().getFullYear() + 2, 11, 15),
      startTime: '06:00 AM',
      organizer: 'Kolkata Frames Collective',
      imageUrl: 'https://images.unsplash.com/photo-1516961642265-531546e84af2?w=800&q=80',
      price: 299,
      capacity: 80,
      availableSeats: 80,
      status: 'published',
      featured: false,
      tags: ['photography', 'heritage', 'kolkata', 'art'],
      createdBy: adminId,
    },
    {
      title: 'Theatre and Storytelling Evening',
      shortDescription: 'An immersive evening of dramatic storytelling and short plays.',
      description: 'Enjoy a captivating evening featuring three short plays directed by emerging directors, followed by an open-mic storytelling session focusing on urban Indian life.',
      category: 'arts',
      venue: 'Prithvi Theatre',
      city: 'Mumbai',
      address: 'Juhu, Mumbai',
      startDate: new Date(new Date().getFullYear() + 2, 8, 28),
      startTime: '07:30 PM',
      organizer: 'Prithvi Arts',
      imageUrl: 'https://images.unsplash.com/photo-1507676184212-d0330a1c5070?w=800&q=80',
      price: 599,
      capacity: 250,
      availableSeats: 250,
      status: 'published',
      featured: true,
      tags: ['theatre', 'drama', 'storytelling', 'arts'],
      createdBy: adminId,
    },
    // FOOD
    {
      title: 'Kolkata Street Food Festival',
      shortDescription: '100+ food stalls featuring street food from every state in India.',
      description: 'A weekend celebration of India\'s incredible street food culture. From Mumbai\'s vada pav to Kolkata\'s phuchka, Delhi\'s chole bhature to Chennai\'s dosas — taste it all under one roof. Live cooking demos and cultural performances.',
      category: 'food',
      venue: 'Eco Park Fairground',
      city: 'Kolkata',
      address: 'New Town',
      startDate: new Date(new Date().getFullYear() + 2, 0, 20),
      endDate: new Date(new Date().getFullYear() + 2, 0, 22),
      startTime: '12:00 PM',
      organizer: 'FoodTrail Events',
      imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
      price: 99,
      capacity: 1500,
      availableSeats: 1500,
      status: 'published',
      featured: true,
      tags: ['food', 'street-food', 'festival', 'culinary'],
      createdBy: adminId,
    },
    {
      title: 'Bengaluru Global Food Weekend',
      shortDescription: 'Experience international cuisines prepared by top chefs.',
      description: 'A massive culinary festival showcasing authentic dishes from over 20 countries. Includes wine tasting sessions, masterclasses by celebrity chefs, and live music.',
      category: 'food',
      venue: 'Palace Grounds',
      city: 'Bengaluru',
      address: 'Jayamahal Road',
      startDate: new Date(new Date().getFullYear() + 2, 10, 5),
      endDate: new Date(new Date().getFullYear() + 2, 10, 7),
      startTime: '11:00 AM',
      organizer: 'Global Bites',
      imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
      price: 299,
      capacity: 2000,
      availableSeats: 2000,
      status: 'published',
      featured: true,
      tags: ['food', 'global', 'festival', 'cuisine'],
      createdBy: adminId,
    },
    {
      title: 'Indian Baking Masterclass',
      shortDescription: 'Learn to bake eggless cakes, cookies, and artisanal breads.',
      description: 'A hands-on masterclass focused on the science of baking with local Indian ingredients. Learn perfect eggless sponges, sourdough basics, and decorative icing techniques. Take home everything you bake!',
      category: 'food',
      venue: 'Koregaon Park Culinary Studio',
      city: 'Pune',
      address: 'Koregaon Park',
      startDate: new Date(new Date().getFullYear() + 2, 5, 14),
      startTime: '10:00 AM',
      organizer: 'Pune Bakehouse',
      imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80',
      price: 799,
      capacity: 50,
      availableSeats: 50,
      status: 'published',
      featured: false,
      tags: ['baking', 'cooking', 'workshop', 'food'],
      createdBy: adminId,
    },
    // HEALTH
    {
      title: 'Mindfulness and Mental Wellness Day',
      shortDescription: 'A day of guided meditation, expert talks, and holistic wellness.',
      description: 'Escape the city stress for a 1-day wellness retreat. Includes guided meditation, talks on mental health by licensed therapists, and stress management workshops. Free entry for all to promote mental health awareness.',
      category: 'health',
      venue: 'Cubbon Park Community Hall',
      city: 'Bengaluru',
      address: 'Cubbon Park',
      startDate: new Date(new Date().getFullYear() + 2, 9, 10),
      startTime: '08:00 AM',
      organizer: 'Inner Peace Foundation',
      imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80',
      price: 0,
      capacity: 200,
      availableSeats: 200,
      status: 'published',
      featured: true,
      tags: ['mental-health', 'wellness', 'meditation', 'retreat'],
      createdBy: adminId,
    },
    {
      title: 'Healthy Lifestyle Expo 2026',
      shortDescription: 'Discover eco-friendly products, organic foods, and fitness trends.',
      description: 'A 2-day expo showcasing sustainable health brands, organic farming produce, fitness equipment, and eco-fashion. Includes panel discussions on nutrition and free health checkups.',
      category: 'health',
      venue: 'Bombay Exhibition Centre',
      city: 'Mumbai',
      address: 'Goregaon',
      startDate: new Date(new Date().getFullYear() + 2, 1, 20),
      endDate: new Date(new Date().getFullYear() + 2, 1, 21),
      startTime: '10:00 AM',
      organizer: 'EcoHealth Network',
      imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80',
      price: 299,
      capacity: 800,
      availableSeats: 800,
      status: 'published',
      featured: false,
      tags: ['health', 'organic', 'fitness', 'expo'],
      createdBy: adminId,
    },
    {
      title: 'Yoga for Beginners Morning Session',
      shortDescription: 'Start your weekend with an energizing sunrise yoga flow.',
      description: 'Join expert instructor Anjali for a soothing morning session focusing on basic asanas, breathing techniques (pranayama), and deep relaxation. Please bring your own yoga mat.',
      category: 'health',
      venue: 'Eco Park',
      city: 'Kolkata',
      address: 'New Town',
      startDate: new Date(new Date().getFullYear() + 2, 3, 5),
      startTime: '06:00 AM',
      organizer: 'Kolkata Yoga Studio',
      imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
      price: 199,
      capacity: 120,
      availableSeats: 120,
      status: 'published',
      featured: true,
      tags: ['yoga', 'fitness', 'health', 'morning'],
      createdBy: adminId,
    },
    // EDUCATION
    {
      title: 'Career and Placement Preparation Summit',
      shortDescription: 'Prepare for top MNC placements with expert mock interviews.',
      description: 'A comprehensive summit for final year college students. Features resume building workshops, aptitude test strategies, group discussion practice, and 1-on-1 mock interviews with HR professionals from top tech and finance firms.',
      category: 'education',
      venue: 'Science City Auditorium',
      city: 'Kolkata',
      address: 'J.B.S Haldane Avenue',
      startDate: new Date(new Date().getFullYear() + 2, 7, 22),
      startTime: '09:00 AM',
      organizer: 'CareerBoost India',
      imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=80',
      price: 0,
      capacity: 500,
      availableSeats: 500,
      status: 'published',
      featured: true,
      tags: ['career', 'education', 'placements', 'students'],
      createdBy: adminId,
    },
    {
      title: 'Study Abroad Information Day',
      shortDescription: 'Meet university representatives from US, UK, Canada, and Australia.',
      description: 'Plan your higher education abroad! Get directly connected with university admission officers, visa consultants, and scholarship experts. On-the-spot profile evaluation available.',
      category: 'education',
      venue: 'India International Centre',
      city: 'Delhi',
      address: 'Max Mueller Marg',
      startDate: new Date(new Date().getFullYear() + 2, 8, 12),
      startTime: '10:00 AM',
      organizer: 'Global Ed Consultants',
      imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
      price: 0,
      capacity: 300,
      availableSeats: 300,
      status: 'published',
      featured: false,
      tags: ['education', 'study-abroad', 'university', 'seminar'],
      createdBy: adminId,
    },
    {
      title: 'Full Stack Developer Career Workshop',
      shortDescription: 'Learn Python, React, and Node.js career pathways.',
      description: 'Perfect for career switchers or junior developers. This workshop breaks down what skills companies are actively hiring for, how to build a strong portfolio, and how to negotiate your first tech salary.',
      category: 'education',
      venue: 'Bengaluru Tech Centre',
      city: 'Bengaluru',
      address: 'Electronic City',
      startDate: new Date(new Date().getFullYear() + 2, 4, 25),
      startTime: '10:00 AM',
      organizer: 'CodeSchool India',
      imageUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80',
      price: 399,
      capacity: 150,
      availableSeats: 150,
      status: 'published',
      featured: true,
      tags: ['python', 'coding', 'career', 'education'],
      createdBy: adminId,
    }
  ];`

const fileStr = fs.readFileSync('backend/src/utils/seed.js', 'utf8');

const regex = /const createEvents \= \(adminId\) \=\> \{\s*const baseDate \= new Date\(\);\s*return \[[\s\S]*?\];\s*\};/;
const replacement = `const createEvents = (adminId) => {
  return ${eventsArray};
};`;

if (!regex.test(fileStr)) {
  console.error('Could not find createEvents array to replace!');
  process.exit(1);
}

const newStr = fileStr.replace(regex, replacement);
fs.writeFileSync('backend/src/utils/seed.js', newStr, 'utf8');
console.log('Successfully updated seed.js with 30 events!');
